#!/bin/bash
##PBS -l nodes=16:ppn=32:xe+64:ppn=16:xk
##PBS -l nodes=8:ppn=16:xk
#PBS -l walltime=10:00:00
#PBS -N cug_2018_inception_imagenet_distributed_train_MBS_32
#PBS -e logs/log.${PBS_JOBNAME}_NN_${PBS_NUM_NODES}_${PBS_JOBID}.err
#PBS -o logs/log.${PBS_JOBNAME}_NN_${PBS_NUM_NODES}_${PBS_JOBID}.out

PREVIOUS_JOBNAME=""
PREVIOUS_JOBID=""

echo "Starting"

if [ -z "${PREVIOUS_JOBNAME}" ] || [ -z "${PREVIOUS_JOBID}" ];
then
echo "Please set the enviromeent variables PREVIOUS_JOBNAME and PREVIOUS_JOBID above then rerun this script"
echo "Exiting"
exit 1
fi

cd $PBS_O_WORKDIR
mkdir -p logs

module load bwpy
module load bwpy-mpi

DATA_DIR="${HOME}/scratch/ImageNet/tf_records"

#UNIQUE_CHECKPOINT_NAME="_$(cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 3 | head -n 1)"

APOUT_LOGS="${PBS_O_WORKDIR}/logs/apout.${PBS_JOBNAME}_${PBS_JOBID}"
echo "output at ${APOUT_LOGS}.*"
CHECKPT_DIR="checkpoint_dir_${PREVIOUS_JOBNAME}_${PREVIOUS_JOBID}.bw"
echo "restoring checkpoint ${CHECKPT_DIR}"


RUN_CMD="python ${PBS_O_WORKDIR}/../BWDistributedTrain/inception_imagenet_validate.py \
--data_dir $DATA_DIR/validation \
--batch_size 1 \
--num_steps $NUM_STEPS \
--num_train_examples 50000 \
--checkpoint_dir ${CHECKPT_DIR}"
echo "Running Comand"
echo ${RUN_CMD}
aprun -b -cc none -n 1 -N 1 $RUN_CMD \
1> ${PBS_O_WORKDIR}/logs/${APOUT_LOGS}.out \
2> ${PBS_O_WORKDIR}/logs/${APOUT_LOGS}.err

echo "Done, Thank you for flying."
